### ISSUE TITLE
tableMaker.js has an undone TODO's

### ISSUE THREAD

**Issue by fearnlj01** [tyrope/bitburner#1]
As per the title of the issue.

**Comment by tyrope** [comment]
For my sanity: [TODO: Fix lineheight.](https://discord.com/channels/415207508303544321/895204896788328448/930188523888336956)

As introduced in commit c4c2b2ee4911436313754d9f0a1df7298be37187

**Comment by tyrope** [comment]
Pending response from the original creator of that lineheight fix function.
https://discord.com/channels/415207508303544321/895204896788328448/936396458658250773

**Comment by fearnlj01** [comment]
Nice job!
