### ISSUE TITLE
[SUGGESTION] Check for SF 3.3

### ISSUE THREAD

**Issue by waffleattack** [tyrope/bitburner#4]
There is no need to buy all the corp apis if sf3.3 is present, as that gives access by default

**Comment by tyrope** [comment]
I already check if we have an unlock before buying it. ;)
https://github.com/tyrope/bitburner/blob/eb38ba7959e74099922bc07605cbd85ad5c5fe6b/corporation.js#L34-L36
(edited link to make sure it stays accurate even after changes)

**Comment by waffleattack** [comment]
oh sorry, i wasn't sure if having sf3.3 gave the upgrades or just lets you use the api without buying upgrades
